### ISSUE TITLE
testing on mac 

### ISSUE THREAD

**Issue by gedw99** [mjl-/mox#28] opened 2023-04-15 10:43 UTC
Trying to get it going on a mac just to test it..

fails with:
"chown receveidid.key" err="chown data/receivedid.key: operation not permitted" pkg=serve path=data/receivedid.key uid=502 gid=0

```
# apple is my user name on the mac... so had to add it.
mox quickstart you@example.com apple

mox serve
l=debug m="autotls setting allowed hostnames" pkg=autotls hostnames=[autoconfig.example.com;mta-sts.example.com;x-macbook-pro-2.local] publicips=[201:90d4:4808:1a92:4898:45f:5842:5d2e]
l=print m="starting as unprivileged user" pkg=serve user=apple uid=502 gid=20 pid=90088
l=error m="chown receveidid.key" err="chown data/receivedid.key: operation not permitted" pkg=serve path=data/receivedid.key uid=502 gid=0
l=fatal m="smtp: listen for smtp" err="no file descriptor for listener [201:90d4:4808:1a92:4898:45f:5842:5d2e]:25" pkg=smtpserver protocol=smtp listener=public
```

**Comment by mjl-** [comment] 2023-04-16 10:00
Could it be you started mox as your regular non-root user? And set variable MOX_SOCKETS?

I've tried reproducing this. First I ran "mox quickstart mjl@test.example mjl".

Then, as user mjl:

```
$ mox serve
l=debug m="autotls setting allowed hostnames" pkg=autotls hostnames=[autoconfig.test.example;mjlbook2.home;mta-sts.test.example] publicips=[0.0.0.0,::]
l=print m="starting as unprivileged user" pkg=serve user=mjl uid=501 gid=20 pid=3367
l=fatal m="mox must be started as root, and will drop privileges after binding required sockets (missing environment variable MOX_SOCKETS)." pkg=mox
```

That message tries to get you to start mox as root. But perhaps you then set MOX_SOCKETS to get past the error message? If I do that:

```
$ MOX_SOCKETS=x mox serve
l=debug m="autotls setting allowed hostnames" pkg=autotls hostnames=[autoconfig.test.example;mjlbook2.home;mta-sts.test.example] publicips=[0.0.0.0,::]
l=print m="starting as unprivileged user" pkg=serve user=mjl uid=501 gid=20 pid=3419
l=error m="chown receveidid.key" err="chown data/receivedid.key: operation not permitted" pkg=serve path=data/receivedid.key uid=501 gid=0
l=fatal m="smtp: listen for smtp" err="no file descriptor for listener 0.0.0.0:25" pkg=smtpserver protocol=smtp listener=public
```

So that's very similar to your message.

If I start as root, it starts up as expected:

```
$ sudo mox serve
Password:
l=debug m="autotls setting allowed hostnames" pkg=autotls hostnames=[autoconfig.test.example;mjlbook2.home;mta-sts.test.example] publicips=[0.0.0.0,::]
l=print m="starting as root, initializing network listeners" pkg=serve version=936a0d5afe16e1080ac55523fd87ae16b90d77c4+modifications pid=3371
l=print m="fixing up permissions, will continue on errors" pkg=serve
l=print m="chown, fixing uid/gid" pkg=serve path=/Users/mjl/code/mox/tmp olduid=501 oldgid=20 newuid=0 newgid=20
[...]
```

If this is indeed what happened, I think we should modify the initial message that tries to get you to run mox as root. It'll probably help if it doesn't say anything about variable MOX_SOCKETS. And I should probably validate the value.

You can also use "mox localserve" to quickly start up a local mox instance for testing.

**Comment by gedw99** [comment] 2023-04-16 18:15
Thanks @mjl- for taking a look.

Will try out a few of these approaches tomorrow and report back.

**Comment by mjl-** [comment] 2023-11-02 15:20
Hi @gedw99, is this issue still relevant? I'm going through the list to see if some can be closed...

**Comment by gedw99** [comment] 2023-11-02 15:39
hey @mjl- 

I don't want to make me a root usr on a Mac: https://support.apple.com/en-gb/HT204012

So the only solution is as you suggested is to run with sudo. 

I am however curious why it needs root ? Is it for certificate installs ?  There is mkcert that I use with caddy and I don't think it needs root. I just would like to try to avoid needed root both for desktops and docker for security reasons. 

Let me know your thoughts...

**Comment by mjl-** [comment] 2023-11-02 15:52
Mox starts as root to listen on "privileged ports" (an old unix concept).
Mox starts as root, binds to ports like 25, 143, 993, etc. Then forks an unprivileged process, passing the listener socket file descriptor. The unprivileged process then accepts connections on those socket file descriptors.

If you just want to run locally for testing, you can run "mox localserve" nowadays. It doesn't listen on privileged ports, but does let you use a lot of the functionality locally.

I don't think there is an option at the moment to start a regular mox as non-root. That could perhaps be useful if you would change all listener ports to be > 1024. But that wouldn't result in a useful SMTP server for incoming deliveries. Or perhaps there is a commonly used mechanism on macOS to let a user bind to all/specific unprivileged ports? Linux has something like that with a capability flag that can be set on a binary. I no longer use that approach because it's always causing trouble with me forgetting to set the magic flag on new binaries during an upgrade and missing highlights of those flags on files...

**Comment by gedw99** [comment] 2023-11-02 15:56
> Mox starts as root to listen on "privileged ports" (an old unix concept). Mox starts as root, binds to ports like 25, 143, 993, etc. Then forks an unprivileged process, passing the listener socket file descriptor. The unprivileged process then accepts connections on those socket file descriptors.

got it... 

> 
> If you just want to run locally for testing, you can run "mox localserve" nowadays. It doesn't listen on privileged ports, but does let you use a lot of the functionality locally.

I wil def try that..

> 
> I don't think there is an option at the moment to start a regular mox as non-root. That could perhaps be useful if you would change all listener ports to be > 1024. But that wouldn't result in a useful SMTP server for incoming deliveries. Or perhaps there is a commonly used mechanism on macOS to let a user bind to all/specific unprivileged ports? 

I don't know sorry. Out of my depth...

> Linux has something like that with a capability flag that can be set on a binary. I no longer use that approach because it's always causing trouble with me forgetting to set the magic flag on new binaries during an upgrade and missing highlights of those flags on files...

**Comment by naturalethic** [comment] 2023-11-02 16:37
I looked into this and [this thread](https://developer.apple.com/forums/thread/674179) discusses the issue and it turns out any user can bind to any port, *however*, you must use the host `0.0.0.0`.  Restrictions still apply if you try to use a specific interface.  Tested this myself and it works.

**Comment by gedw99** [comment] 2023-11-02 16:39
Nice one ☝️ 

do you have a Mac ? Or should I try it tomorrow?

**Comment by naturalethic** [comment] 2023-11-02 16:40
Yes, I do have a mac, and tested it.  It works.

**Comment by naturalethic** [comment] 2023-11-02 16:45
Seems to be you should just have to change this part of your config:
```
		# Use 0.0.0.0 to listen on all IPv4 and/or :: to listen on all IPv6 addresses, but
		# it is better to explicitly specify the IPs you want to use for email, as mox
		# will make sure outgoing connections will only be made from one of those IPs.
		IPs:
			- 127.0.0.1  # <--- change to 0.0.0.0
```
There are potential security implications if expose everything to the public, so consider that.

**Comment by mjl-** [comment] 2023-11-02 17:11
@naturalethic are you running this as non-root? or are you using mox localserve with privileged ports?

@gedw99 are you really using a full mox install for mail delivery on macos? i'm assuming this isn't a macos server (i think macos is a desktop-only OS nowadays?). i'm trying to figure out what the use case is, and whether/where we can add some info to users so they don't run into trouble.

**Comment by gedw99** [comment] 2023-11-02 17:13
For me it’s just for debugging it.

**Comment by naturalethic** [comment] 2023-11-02 17:24
@mjl- I didn't test mox itself, I tested launching a service (vite in this case) on 0.0.0.0:80 worked as a non-root user, and verified the same did not work for any other host ip configuration, thus the linked thread is accurate in its information.

@gedw99 If you're just testing, why not use `localserve`

**Comment by mjl-** [comment] 2024-04-16 19:08
Closing this issue, it's been a while, there are workarounds, and doesn't seem we can do much for the situation. Feel free to reopen if there's still something to do.

**Closed by mjl-** 2024-04-16 19:08 UTC

**Comment by gedw99** [comment] 2024-04-19 01:04
I did not know about ``` localserve ```
