### ISSUE TITLE
Mail landing in spam folder (Outlook, Proton ..)

### ISSUE THREAD

**Issue by hymalsurk** [mjl-/mox#177] opened 2024-06-15 19:54 UTC
Hi there, 
I am experiencing a problem I cannot explain. 
Mail-tester, internet.nl, tools.xmox.nl, integrated dns checks say that my configuration is good and i score 100% everywhere. But I still end up in junk on some providers (outlook and proton) but on others (gmail, gmx) everything works fine. 
IPs are clean. 
Help would be really appreciated.

**Comment by mjl-** [comment] 2024-06-16 19:29
hi @hymalsurk, typical reasons for getting into a spam folder are:
- the domain you're sending from was newly registered. many mail services treat "new" domains as suspicious for the first month after registering. a subdomain of an existing domain should help.
- ip addresses sometimes have old reputation, or suffer from bad reputation of other nearby ip's. especially on many cheaper vps providers this can be a reason for being blocked.
- some mail services simply aren't very good at junk filtering and block anything new. especially the free outlook addresses do this (the commercial outlook is usually better). outlook/microsoft has a page where you can register your ip, and ask for being unblocked (after which they claim they aren't seeing anything that affects the reputation, then you ask again, they say the same, but the problem is solved).

perhaps there's something special or unusual about your setup that causes your messages to be treated differently? you could also look at the reason proton and outlook give for marking your message as junk (if they provide any).

**Comment by mjl-** [comment] 2024-08-02 14:24
I hope you've been able to get this resolved, closing issue for now. Please leave a comment if any changes/actions you've made/done improved the junk analysis problem. Feel free to reopen if you want to discuss further.

**Closed by mjl-** 2024-08-02 14:24 UTC
