### ISSUE TITLE
custom certificate file and key

### ISSUE THREAD

**Issue by hismailbulut** [mjl-/mox#2] opened 2023-02-21 21:06 UTC
Hi, first of all thank you for this great project.

I am trying to use mox on my vps with an api already serving at http and https ports. I want to use both of them at same server. I started mox with `mox quickstart mail@mydomain.com` and edited the mox.conf as suggested at docs and replaced tls config with my certificate file path and private key. The mox works well if I use ACME but it panics when I change it like this:
```yaml
DataDir: ../data
LogLevel: error
Hostname: mail.mydomain.com
CheckUpdates: true
AdminPasswordFile: adminpasswd

Listeners:
  internal:
    IPs:
      - 127.0.0.1
      - ::1
      - <some other public ip's>
    Hostname: localhost
    TLS:
      ACME: letsencrypt
      KeyCerts:
        - 
          CertFile: /path/to/the/cert
          KeyFile: /path/to/the/key
    SMTPMaxMessageSize: 1048576
    AccountHTTP:
      Enabled: false
    AdminHTTP:
      Enabled: false
    MetricsHTTP:
      Enabled: false
  public:
    IPs:
      - 0.0.0.0
      - ::
    TLS:
      ACME: letsencrypt
    SMTP:
      Enabled: true
    Submissions:
      Enabled: true
    IMAPS:
      Enabled: true
    AutoconfigHTTPS:
      Enabled: false
    MTASTSHTTPS:
      Enabled: false
Postmaster:
  Account: mail
  Mailbox: Postmaster
```
And this is the panic message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8e1c62]

goroutine 1 [running]:
github.com/mjl-/mox/mox-.PrepareStaticConfig({0x0?, 0x0?}, {0xca4e52, 0xf}, 0xc0000bd900, 0x0)
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/mox-/config.go:440 +0xf42
github.com/mjl-/mox/mox-.ParseConfig({0xddcd58, 0xc000038080}, {0xca4e52, 0xf}, 0x0)
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/mox-/config.go:347 +0x52c
github.com/mjl-/mox/mox-.LoadConfig({0xddcd58?, 0xc000038080?})
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/mox-/config.go:310 +0x4e
github.com/mjl-/mox/mox-.MustLoadConfig()
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/mox-/config.go:295 +0xc5
main.cmdServe(0xc0000b6f80)
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/serve.go:135 +0x7c
main.main()
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/main.go:407 +0x922
```
It doesnt panic if I change the line after KeyCerts to something like this 
```yaml
KeyCerts:
  - cert:
```
but this time it gives this error:
```
fatal: "loading config file": "parsing config/mox.conf: :<line number of "- cert:">: expected indent" (pkg: mox)
```

**Comment by mjl-** [comment] 2023-02-21 21:21
Thanks for the report! I'll look into why that panic is happening. But if you aren't using ACME, you should remove the "ACME: letsencrypt" lines. That may already get you further.

And the reason it doesn't panic with your KeyCerts change is that it makes the configuration file invalid (invalid syntax), so it never makes it to the code that panics. The syntax may look a bit weird, this isn't yaml, so you really need to use something like this:

```
      KeyCerts:
        - 
          CertFile: /path/to/the/cert
          KeyFile: /path/to/the/key
```

**Comment by mjl-** [comment] 2023-02-21 21:40
I'm getting different errors with the config file you posted:

```
multiple errors:
listener "internal": cannot have ACME and static key/certificates
listener "public": unknown ACME provider "letsencrypt"
```

Is there more in the mox.conf file? I would at least expect the ACME provider named "letsencrypt". You could also send me the config files (minus keys of course) to mechiel@ueber.net so I can try to reproduce this panic.

But a few more observations:
- Listener "internal" probably doesn't need TLS? At least it is not being used: AccountHTTP, AdminHTTP and MetricsHTTP are all plain text, not TLS. So you can probably just remove the whole TLS section from "internal". Or better, move the KeyCerts to "public".
- The "public" listener does need TLS: The "s" or "S" at the end of: Submissions, IMAPS, AutoconfigHTTPS, MTASTSHTTPS. There should be no ACME there, only the KeyCerts config.
- Did you put 0.0.0.0 and :: in the IPs for listener "public" to not have to post them here in the issue? It's best to leave the actual external IPs configured. Because then mox only uses those IPs for outgoing connections, such as for SMTP delivery. Mox can check if its IPs have proper reverse DNS configured (pretty much required if you want mail delivery to succeed reliably), but that only helps if no other IPs are used for outgoing connections.

**Comment by mjl-** [comment] 2023-02-21 22:00
Ah, I was testing with "mox config test", which has a different code path. Mox is continuing on config errors, and then dereferencing the unset acme variable. I'll go fix that. Hopefully removing the ACME-line in the config makes mox start with your setup.

**Comment by mjl-** [comment] 2023-02-22 22:33
Thanks for the clear report and for sticking with mox!

http/web.go was incorrectly initializing acme on port 443 even with only the keycerts configured. Should be fixed in latest commit. Could you give it another try?

Btw, with AutoconfigHTTPS and especially MTASTSHTTPS disabled, you should remove the relevant DNS records.
Or you could let mox listen on a higher port (e.g. add "Port: 1443") and forward (reverse proxy) traffic from your existing webserver to that port (the reverse proxy must connect with TLS at the moment).

I'm also considering adding a simple reverse http proxy to mox, so mox can be in charge, and forward all traffic not meant for it to configured addresses, while doing TLS with ACME. Not sure if folks will find it a comfortable idea that their web traffic is handled by their mail server though...

**Comment by hismailbulut** [comment] 2023-02-23 21:06
Latest patch solved my issue. Thank you so much :)
I may consider supporting AutoconfigHTTPS and MTASTSHTTPS on my server but currently this setup is mostly enough for me.
Most users already use their own reverse proxy or a well known one, but for simple operations it might be nice if mox supports it. I don't know much about this as I'm not an expert though.

**Closed** 2023-02-24 09:08 UTC
